fix promise
LISBON11/svgo pull request #1
Opened 2017-08-10 17:59 UTC by LISBON11

2017-08-16 00:03 UTC, LISBON11 commented
@DudaGod

2017-08-16 00:03 UTC, LISBON11 commented
@tadatuta

2017-08-16 00:08 UTC, DudaGod commented on test/coa/_index.js
> +    it.only('should change plugin state', function (done) {
ONLY!!!!!111111

2017-08-16 01:10 UTC, DudaGod requested changes

2017-08-16 01:10 UTC, DudaGod commented on lib/svgo/coa.js
> +            return new Promise(function(resolve, reject) {
тут callback через `function` написала, ниже через стрелочную. Где же консистентность?

2017-08-16 01:10 UTC, DudaGod commented on lib/svgo/coa.js
> +                            return;
лишний `return`

2017-08-16 01:10 UTC, DudaGod commented on lib/svgo/coa.js
> -    }, error => console.error(error));
почему это выпилила? Вместо этого можно `catch` добавить

2017-08-16 01:10 UTC, DudaGod commented on lib/svgo/coa.js
> +            resolve();
вот так вложенность меньше будет
```js
if (config.quiet) {
  return resolve();
}

printTimeInfo(time);  // print time info
printProfitInfo(inBytes, outBytes);  // print optimization profit info
```

2017-08-16 01:10 UTC, DudaGod commented on lib/svgo/coa.js
> +                return;
```js
return reject(err);
```

2017-08-16 01:10 UTC, DudaGod commented on lib/svgo/coa.js
> +                return;
```js
return resolve()
```

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +        '../../lib/svgo/coa.js').api,
```js
SVGO = require(process.env.COVERAGE
    ? '../../lib-cov/svgo/coa.js'
    : '../../lib/svgo/coa.js').api,
```

не понятно зачем в SVGO в upperCase указан

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +    PATH = require('path'),
зачем в upperCase? Это же модуль, а не константа

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +    svgPath = PATH.resolve(__dirname,'test.svg');
раздели `test.svg` отбей пробелом от запятой

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +            .catch();
по моему пустой `catch` лишний

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +            .then(() => { /Currently available plugins:/.test(output) ? done() : null; })
лишняя точка с запятой после `null`
И если пишешь тернарник в одну строку зачем тебе фигурные кавычки?

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +    it('should show plugins', function (done) {
На самом деле ты тут проверяешь, что в оутпуте содержится строка - `Currently available plugins:`. При этом ни один плагин может не показаться

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +    it('should throw error in opts.config when is not parsed string as value', function (done) {
`should throw AN error if "config" can not be parsed`

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +            .catch();
лишние пустые `catch`-и

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +    it('should optimize file', function (done) {
на самом деле ты тут во всех тестах проверяешь, что промис зарезолвился. А правильно файл соптимизировался или нет - неизвестно

2017-08-16 01:10 UTC, DudaGod commented on test/coa/_index.js
> +    it('string input', function (done) {
should... ?

2017-08-16 01:10 UTC, DudaGod commented on test/coa/test.svg
> +<!--! https://github.com/svg/svgo--><!--! SVGO project logo by Yegor Bolshakov (http://xizzzy.ru/)--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="512" hei
нет перевод строки в конце файла и зачем тебе вообще этот файл?

2017-08-16 01:10 UTC, DudaGod commented on lib/svgo/coa.js
> +                                        if (!config.quiet) {
инвертируй условие, тогда вложенность меньше получится

2017-08-16 01:10 UTC, DudaGod commented on lib/svgo/coa.js
> +                                            return;
```js
switch(err.code) {
  case 'ENOENT':
    return mkdirp(output, writeOutput);
  case 'ENOTDIR':
    return reject(`Error: output '${output}' is not a directory.`);
  default:
    return reject(err);
}
```

2017-08-16 01:10 UTC, DudaGod commented on lib/svgo/coa.js
>                                  return;
```js
return reject(err);
```

2017-08-16 10:05 UTC, LISBON11 commented on lib/svgo/coa.js
> +            resolve();
Так резолвить надо в любом случае,  вы выводить инфу только если !config.quiet

2017-08-16 10:05 UTC, LISBON11 commented on lib/svgo/coa.js
> +                            return;
Вроде не лишний. 
Если  срабатывает любой из последних двух кейсов
```js
else if (err.code === 'ENOENT')
     reject(`Error: no such file or directory '${input}'.`);
else
     reject(err);
```
то  не надо дергать некст
```js
optimizeFromString(data, config, opts.datauri, input, output)
    .then(resolve)
    .catch(reject);
```

2017-08-16 10:21 UTC, LISBON11 commented on test/coa/_index.js
> +    it('should show plugins', function (done) {
Да, но в coa.js в  ```js function showAvailablePlugins() {...} ```  по факту нет проверки на пустой список плагинов

2017-08-16 10:29 UTC, LISBON11 commented on test/coa/test.svg
> +<!--! https://github.com/svg/svgo--><!--! SVGO project logo by Yegor Bolshakov (http://xizzzy.ru/)--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="512" hei
Это свгшка для тестов

2017-08-16 11:37 UTC, DudaGod commented on lib/svgo/coa.js
> +                            return;
ну выглядит костыльно же.
Напиши через `switch` например:
```js
if (err) {
  switch(err.code) {
    case 'EISDIR':
      return optimizeFolder(input, config, output)
        .then(resolve)
        .catch(reject);
    case: 'ENOENT':
      return reject(`Error: no such file or directory '${input}'.`);
    default:
      return reject(err);
  }
}
```

2017-08-16 16:20 UTC, tadatuta commented on lib/svgo/coa.js
> -            process.exit(0);
revert

2017-08-16 16:20 UTC, tadatuta commented on test/coa/_index.js
> +    })
;

2017-08-16 16:20 UTC, tadatuta commented on test/coa/_index.js
> +        }, 0)
;

2017-08-16 16:20 UTC, tadatuta commented on test/coa/_index.js
> +                fs.readFileSync(folderPath + '/' + fileName).length : 0)
* `;` is missing
* use `stat`

2017-08-16 16:20 UTC, tadatuta commented on test/coa/_index.js
> +        let fileNames = fs.readdirSync(folderPath);
`const`

2017-08-16 16:20 UTC, tadatuta commented on test/coa/_index.js
> +            return initWeight + (/.svg/.test(fileName) ?
```js
if (!/.svg/.test(fileName)) return initWeight;
```

2017-08-16 16:20 UTC, tadatuta commented on test/coa/_index.js
> +            .then(() => {/Currently available plugins:/.test(output) ? done() : null })
```js
.then(() => done(/Currently available plugins:/.test(output) ? null : 'SOME TEXT');
```

2017-08-16 16:20 UTC, tadatuta commented on test/coa/_index.js
> +            .then(() => { /Error: Couldn't parse config JSON/.test(output) ? done() : null; })
?

2017-08-16 16:20 UTC, tadatuta commented on test/coa/_index.js
> +    it('should work ptoperly with string input', function(done) {
p**t**operly

2017-08-16 16:20 UTC, tadatuta commented on test/coa/_index.js
> +            .catch();
done

2017-08-23 14:36 UTC, tadatuta commented on test/coa/_index.js
> +        return fileNames.reduce((initWeight, fileName) => {
fs.readdirSync(folderPath)

2017-08-23 14:36 UTC, tadatuta commented on test/coa/_index.js
> +        if(fs.existsSync("ololo")) {
temp

2017-08-23 14:36 UTC, tadatuta commented on test/coa/_index.js
> +        replaceConsoleLog();
describe('stdout')

2017-10-13 10:40 UTC, merged